<a href="https://colab.research.google.com/github/Sakshi-coder1/workco/blob/main/Excel_to_Python_Analytics_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [7]:
#importing libararies
import numpy as np
import pandas as pd

In [9]:
#read my dataset
df=pd.read_excel('/content/sales.xlsx')

In [10]:
#view the first 5 records
df.head()

   Order ID       Date Product     Category Region  Quantity  Price   Sales
0      1001 2026-01-01  Laptop  Electronics  North         2  50000  100000
1      1002 2026-01-02   Mouse  Electronics  South         5    500    2500
2      1003 2026-01-03   Chair    Furniture   East         3   4000   12000
3      1004 2026-01-04  Laptop  Electronics   West         1  50000   50000
4      1005 2026-01-05    Desk    Furniture  North         2  10000   20000

In [11]:
df.tail()

   Order ID       Date Product     Category Region  Quantity  Price  Sales
3      1004 2026-01-04  Laptop  Electronics   West         1  50000  50000
4      1005 2026-01-05    Desk    Furniture  North         2  10000  20000
5      1006 2026-01-06   Mouse  Electronics   East        10    500   5000
6      1007 2026-01-07   Chair    Furniture  South         4   4000  16000
7      1008 2026-01-08  Laptop  Electronics  North         1  50000  50000

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 8 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Order ID  8 non-null      int64
 1   Date      8 non-null      datetime64[ns]
 2   Product   8 non-null      object
 3   Category  8 non-null      object
 4   Region    8 non-null      object
 5   Quantity  8 non-null      int64
 6   Price     8 non-null      int64
 7   Sales     8 non-null      int64
dtypes: datetime64[ns](1), int64(4), object(3)
memory usage: 644.0+ bytes

In [13]:
df.describe()

         Order ID                 Date   Quantity         Price          Sales
count     8.00000                    8   8.000000      8.000000       8.000000
mean   1004.50000  2026-01-04 12:00:00   3.500000  21125.000000   31937.500000
min    1001.00000  2026-01-01 00:00:00   1.000000    500.000000    2500.000000
25%    1002.75000  2026-01-02 18:00:00   1.750000   3125.000000   10250.000000
50%    1004.50000  2026-01-04 12:00:00   2.500000   7000.000000   18000.000000
75%    1006.25000  2026-01-06 06:00:00   4.250000  50000.000000   50000.000000
max    1008.00000  2026-01-08 00:00:00  10.000000  50000.000000  100000.000000
std       2.44949                  NaN   2.976095  24090.232164   33104.205063

In [15]:
df.shape

(8, 8)

In [16]:
df.columns

Index(['Order ID', 'Date', 'Product', 'Category', 'Region', 'Quantity',
       'Price', 'Sales'],
      dtype='object')

In [17]:
#Filtering
df[df['Region']=="North"]

   Order ID       Date Product     Category Region  Quantity  Price   Sales
0      1001 2026-01-01  Laptop  Electronics  North         2  50000  100000
4      1005 2026-01-05    Desk    Furniture  North         2  10000   20000
7      1008 2026-01-08  Laptop  Electronics  North         1  50000   50000

In [18]:
# Filter electonics category
df[df['Category']=="Electronics"]

   Order ID       Date Product     Category Region  Quantity  Price   Sales
0      1001 2026-01-01  Laptop  Electronics  North         2  50000  100000
1      1002 2026-01-02   Mouse  Electronics  South         5    500    2500
3      1004 2026-01-04  Laptop  Electronics   West         1  50000   50000
5      1006 2026-01-06   Mouse  Electronics   East        10    500    5000
7      1008 2026-01-08  Laptop  Electronics  North         1  50000   50000

In [19]:
# Filter sales where sales> 20000
df[df['Sales']>20000]

   Order ID       Date Product     Category Region  Quantity  Price   Sales
0      1001 2026-01-01  Laptop  Electronics  North         2  50000  100000
3      1004 2026-01-04  Laptop  Electronics   West         1  50000   50000
7      1008 2026-01-08  Laptop  Electronics  North         1  50000   50000

In [20]:
# Sorting sales in decending order
df.sort_values("Sales",ascending=False)

   Order ID       Date Product     Category Region  Quantity  Price   Sales
0      1001 2026-01-01  Laptop  Electronics  North         2  50000  100000
3      1004 2026-01-04  Laptop  Electronics   West         1  50000   50000
7      1008 2026-01-08  Laptop  Electronics  North         1  50000   50000
4      1005 2026-01-05    Desk    Furniture  North         2  10000   20000
6      1007 2026-01-07   Chair    Furniture  South         4   4000   16000
2      1003 2026-01-03   Chair    Furniture   East         3   4000   12000
5      1006 2026-01-06   Mouse  Electronics   East        10    500    5000
1      1002 2026-01-02   Mouse  Electronics  South         5    500    2500

In [21]:
# Sort quantity in a way taht highest quntity appears at last
df.sort_values("Quantity",ascending=True)

   Order ID       Date Product     Category Region  Quantity  Price   Sales
3      1004 2026-01-04  Laptop  Electronics   West         1  50000   50000
7      1008 2026-01-08  Laptop  Electronics  North         1  50000   50000
4      1005 2026-01-05    Desk    Furniture  North         2  10000   20000
0      1001 2026-01-01  Laptop  Electronics  North         2  50000  100000
2      1003 2026-01-03   Chair    Furniture   East         3   4000   12000
6      1007 2026-01-07   Chair    Furniture  South         4   4000   16000
1      1002 2026-01-02   Mouse  Electronics  South         5    500    2500
5      1006 2026-01-06   Mouse  Electronics   East        10    500    5000

In [22]:
# KPI Values
# Total Revenue
df['Sales'].sum()

np.int64(255500)

In [27]:
# Total Orders
df['Order ID'].count()

np.int64(8)

In [29]:
# Average sales
df['Sales'].mean()

np.float64(31937.5)

In [30]:
# Highest Sales
df['Sales'].max()

100000

In [31]:
# Lowest Sale
df['Sales'].min()

2500